create table if not exists public.boardings (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  district text not null,
  monthly_rent numeric(12, 2) not null check (monthly_rent > 0),
  room_type text not null,
  gender_preference text not null,
  contact_number text not null,
  wifi boolean not null default false,
  kitchen boolean not null default false,
  attached_bathroom boolean not null default false,
  parking boolean not null default false,
  distance_km numeric(6, 2) check (distance_km >= 0),
  description text,
  created_at timestamptz not null default now()
);
